/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekimini.gui;

import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import wekimini.Wekinator;

/**
 *
 * @author louismccallum
 */
public class AutomaticFeaturesEditor extends javax.swing.JFrame {

    Wekinator w;
    
    public AutomaticFeaturesEditor(Wekinator w) {
        initComponents();
        this.w = w;
        setupTable(w.getDataManager().selectedFeatureNames);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setupTable(String[][] selectedFeatures)
    {
        FeatureTableModel model = new FeatureTableModel(selectedFeatures);
        jTable1.setModel(model);
    }
    
    public class FeatureTableModel extends AbstractTableModel
    {
        private String[][] features;
        
        public FeatureTableModel(String[][] features)
        {
            this.features = features;
        }
        
        @Override
        public int getRowCount() {
            int max = Integer.MIN_VALUE;
            for(String [] f:features)
            {
                if(f.length > max)
                {
                    max = f.length;
                }
            }
            return max;
        }

        @Override
        public int getColumnCount() {
            return features.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return features[columnIndex][rowIndex];
        }
        
        @Override
        public void setValueAt(Object value, int row, int col) {
            features[row][col] = (String)value;
            fireTableCellUpdated(row, col);
        }
        
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
        
        @Override
        public String getColumnName(int col) {
            return "output " + (col + 1);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        w.getDataManager().selectFeaturesAutomatically();
        setupTable(w.getDataManager().selectedFeatureNames);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
