/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wekimini.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import wekimini.modifiers.Feature;

/**
 *
 * @author louismccallum
 */
public class FeatureSetPlotPanel extends javax.swing.JPanel {
    private BufferedImage image;
    private double w = 1;
    private double imageHeight = 1;
    private double plotHeight = 1;
    FeatureSetPlotItem[] features;
    double librarySize = 202;
    private static final double RADIUS = 15;
    
    public FeatureSetPlotPanel(){
        initComponents();
    }
    
    public void setDimensions(int w, int h)
    {
        this.w = w;
        imageHeight = h;
        plotHeight = (h * 0.875) - 10.0;
        image = new BufferedImage(w, (int)imageHeight, BufferedImage.TYPE_INT_ARGB);
        setBackground(Color.white);
        clear();
    }
    
    public void update(FeatureSetPlotItem[] features)
    {
        this.features = features;
        repaint();
    }
    
    private double yForFeature(Feature ft)
    {
        double y = 0;
        double totalSensors = 7;
        switch(ft.sensor) {
            case ACCX:
                y = plotHeight * (0 / totalSensors);
                break;
            case ACCY:
                y = plotHeight * (1 / totalSensors);
                break;
            case ACCZ:
                y = plotHeight * (2 / totalSensors);
                break;
            case GYROX:
                y = plotHeight * (3 / totalSensors);
                break;
            case GYROY:
                y = plotHeight * (4 / totalSensors);
                break;
            case GYROZ:
                y = plotHeight * (5 / totalSensors);
                break;
            case MULTIPLE:
                y = plotHeight * (6 / totalSensors);
                break;
        }
        return y;
    }
    
    public Color colorForFeature(Feature ft)
    {
        if(ft.tags.contains("Mean"))
        {
            return Color.BLUE;
        }
        else if(ft.tags.contains("Standard Deviation"))
        {
            return Color.RED;
        }
        else if(ft.tags.contains("Energy"))
        {
            return Color.ORANGE;
        }
        else if(ft.tags.contains("Max"))
        {
            return Color.GREEN;
        }
        else if(ft.tags.contains("Min"))
        {
            return Color.BLACK;
        }
        else if(ft.tags.contains("FFT"))
        {
            return Color.MAGENTA;
        }
        else if(ft.tags.contains("1st Order Diff"))
        {
            return Color.PINK;
        }
        else if(ft.tags.contains("IQR"))
        {
            return Color.CYAN;
        }
        return Color.BLUE;
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        if (image != null)
        {
            g.drawImage(image, 0, 0, null);
        }
        Graphics2D g2d = (Graphics2D)g;
        for(FeatureSetPlotItem f:features)
        {
            double x = (f.ranking/librarySize) * w;
            double y = yForFeature(f.feature);
            g2d.setColor(colorForFeature(f.feature));
            g2d.fill(new Ellipse2D.Double(x, y, RADIUS, RADIUS));
        }
    }
    
    public void clear()
    {
        createEmptyImage((int)w);
        repaint();
    }

    private void createEmptyImage(int width)
    {
        image = new BufferedImage(width, (int)imageHeight, BufferedImage.TYPE_INT_ARGB);
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
