/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekimini.gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author louismccallum
 */
public class FilterFeaturesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterFeaturesPanel
     */
    public FilterFeaturesPanel() {
        initComponents();
        availableFiltersTable.setTableHeader(null);
    }
    
    public void setUpTables()
    {
//        availableFiltersTable.setRowHeight(140/4);
//        
//        String[] combined = new String[] {"All", "Above Thresh", "Below Thresh", "None", "Accelerometer", "Gyroscope",
//                "AccelerometerX", "AccelerometerY", "AccelerometerZ", "GyroscopeX", "GyroscopeY", "GyroscopeZ", 
//                "Raw", "Buffer", "Mean", "1st Order Diff", "FFT", "Max", "Min",
//                "Energy", "IQR", "Correlation", "Standard Deviation", "Magnitude"
//        };
//        availableFiltersTable.setModel(new NewFeaturesPanel.FiltersTableModel(combined));
//        availableFiltersTable.setDefaultRenderer(String.class, new NewFeaturesPanel.FiltersTableRenderer());
//        
//        MouseMotionListener tableMouseMotionListener = new MouseAdapter() {
//            @Override
//            public void mouseMoved(MouseEvent e) {
//                int row = availableFiltersTable.rowAtPoint(e.getPoint());
//                int col = availableFiltersTable.columnAtPoint(e.getPoint());
//                highlightedTag = (String)availableFiltersTable.getModel().getValueAt(row, col);
//                //System.out.println("hover on " + highlightedTag);
//                availableFiltersTable.repaint();
//            }
//        };
//        availableFiltersTable.addMouseMotionListener(tableMouseMotionListener);
//        
//        MouseListener tableMouseListener = new MouseAdapter() {
//            @Override
//            public void mousePressed(MouseEvent e) {
//                int row = availableFiltersTable.rowAtPoint(e.getPoint());
//                int col = availableFiltersTable.columnAtPoint(e.getPoint());
//                String tag = (String)availableFiltersTable.getModel().getValueAt(row, col);
//                if(tag.equals("All"))
//                {
//                    selectAll();
//                }
//                else if(tag.equals("Above Thresh"))
//                {
//                    selectThresh(true);
//                }
//                else if(tag.equals("Below Thresh"))
//                {
//                    selectThresh(false);
//                }
//                else if(tag.equals("None"))
//                {
//                    clearSelection();
//                }
//                else if(selectedFilters.contains(tag))
//                {
//                    selectedFilters.remove(tag);
//                    updateFilters();
//                }
//                else
//                {
//                    selectedFilters.add(tag);
//                    updateFilters();
//                }
//            }
//        };
//        availableFiltersTable.addMouseListener(tableMouseListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        availableFiltersTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        selectAllButton = new javax.swing.JButton();
        addRemoveButtonPressed = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        availableFiltersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(availableFiltersTable);

        jLabel6.setText("Input");

        jLabel7.setText("Operation");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        selectAllButton.setText("Select All");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        addRemoveButtonPressed.setText("Add");
        addRemoveButtonPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveButtonPressedActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(selectAllButton)
                                        .addGap(279, 279, 279))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addRemoveButtonPressed)
                                        .addGap(290, 290, 290))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addRemoveButtonPressed))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void addRemoveButtonPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveButtonPressedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRemoveButtonPressedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRemoveButtonPressed;
    private javax.swing.JTable availableFiltersTable;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton selectAllButton;
    // End of variables declaration//GEN-END:variables
}
