/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekimini.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import wekimini.InputManager;
import wekimini.Wekinator;
import wekimini.util.WeakListenerSupport;

/**
 *
 * @author rebecca
 */
public class InputMonitor extends javax.swing.JFrame {

    private final Wekinator w;
    private final WeakListenerSupport wls = new WeakListenerSupport();
//    private final InputManager.InputListener listener = this::update;
        private final InputManager.InputListener listener = new InputManager.InputListener() {

        @Override
        public void update(double[] vals) {
               updateValues(vals);
        }

        @Override
        public void notifyInputError() {
        }

        @Override
        public void updateBundle(List<List<Double>> values) {
            int numPoints = values.size();
            List<Double> last = values.get(values.size()-1);
            if (numPoints > 0) {
                double[] vals = new double[rows.size()];
                for (int i = 0; i < vals.length; i++) {
                    vals[i] = last.get(i);
                }
                updateValues(vals);
            }
        }
    };

    
    private final List<NameValueRow> rows = new ArrayList<>();
    private final ImageIcon onIcon = new ImageIcon(getClass().getResource("/wekimini/icons/greenlight2.png")); // NOI18N
    private final ImageIcon offIcon = new ImageIcon(getClass().getResource("/wekimini/icons/greylight2.png")); // NOI18N
    private ScheduledExecutorService scheduledExecutorService = Executors.newScheduledThreadPool(1);
    private ScheduledFuture scheduledFuture;

    /**
     * Creates new form OSCInputStatusFrame
     */
    public InputMonitor() {
        initComponents();
        this.w = null;
    }

    public InputMonitor(final Wekinator w) {
        initComponents();
        this.w = w;
        String s1 = "Listening for " + w.getInputManager().getNumInputs() + " inputs "
                + "on port " + w.getOSCReceiver().getReceivePort();
        label1.setText(s1);
        String s2 = "with message " + w.getInputManager().getOSCInputGroup().getOscMessage();
        label2.setText(s2);
        double[] current = w.getInputManager().getInputValues();
        addPanels(current.length);
        for (int i = 0; i < current.length; i++) {
            rows.get(i).setValue(current[i]);
        }

        scheduledFuture = scheduledExecutorService.scheduleWithFixedDelay(new Runnable() {
            @Override
            public void run() {
                labelIndicator.setIcon(offIcon);
            }
        }, 1, 1, TimeUnit.SECONDS);

        w.getInputManager().addInputValueListener(listener);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                w.getInputManager().removeInputValueListener(listener);
            }
        });

    }

    private void addPanels(int howMany) {
        panelInputsParent.removeAll();
        for (int i = 0; i < howMany; i++) {
            NameValueRow r = new NameValueRow((i + 1) + ". " + w.getInputManager().getInputNames()[i]);
            rows.add(r);
            panelInputsParent.add(r);
        }
        panelInputsParent.repaint();
    }

    private void updateValues(double[] vals) {
        labelIndicator.setIcon(onIcon);
        for (int i = 0; i < vals.length; i++) {
            rows.get(i).setValue(vals[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelInputsParent = new javax.swing.JPanel();
        nameValueRow1 = new wekimini.gui.NameValueRow();
        nameValueRow2 = new wekimini.gui.NameValueRow();
        nameValueRow3 = new wekimini.gui.NameValueRow();
        nameValueRow4 = new wekimini.gui.NameValueRow();
        nameValueRow5 = new wekimini.gui.NameValueRow();
        nameValueRow7 = new wekimini.gui.NameValueRow();
        nameValueRow6 = new wekimini.gui.NameValueRow();
        label2 = new javax.swing.JLabel();
        labelIndicator = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Monitor");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label1.setText("Listening for 6 inputs on port 6448\n");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelInputsParent.setBackground(new java.awt.Color(255, 255, 255));
        panelInputsParent.setLayout(new javax.swing.BoxLayout(panelInputsParent, javax.swing.BoxLayout.Y_AXIS));
        panelInputsParent.add(nameValueRow1);
        panelInputsParent.add(nameValueRow2);
        panelInputsParent.add(nameValueRow3);
        panelInputsParent.add(nameValueRow4);
        panelInputsParent.add(nameValueRow5);
        panelInputsParent.add(nameValueRow7);
        panelInputsParent.add(nameValueRow6);

        jScrollPane1.setViewportView(panelInputsParent);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        label2.setText("Input message /wek/inputs");

        labelIndicator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wekimini/icons/greylight2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelIndicator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelIndicator;
    private wekimini.gui.NameValueRow nameValueRow1;
    private wekimini.gui.NameValueRow nameValueRow2;
    private wekimini.gui.NameValueRow nameValueRow3;
    private wekimini.gui.NameValueRow nameValueRow4;
    private wekimini.gui.NameValueRow nameValueRow5;
    private wekimini.gui.NameValueRow nameValueRow6;
    private wekimini.gui.NameValueRow nameValueRow7;
    private javax.swing.JPanel panelInputsParent;
    // End of variables declaration//GEN-END:variables
}
