/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wekimini.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import wekimini.gui.PlotFrame.PlotRowModel;

/**
 *
 * @author louismccallum
 */
public class PlotRowPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlotRowPanel
     */
    
    public PlotRowModel model;
    private String[] outputs = new String[0];
    private String[] features = new String[0];
    private String state;
    private PlotRowDelegate delegate;
    
    public PlotRowPanel(String[] outputs, String[] features, PlotRowDelegate delegate) {
        initComponents();
        this.delegate = delegate;
        this.outputs = outputs;
        this.features = features;
        for(String output : outputs)
        {
            outputComboBox.addItem(output);
        }
        
        for(String feature : features)
        {
            featureComboBox.addItem(feature);
        }
    }
    
    public void updateModel(PlotRowModel model)
    {
        this.model = model;
        plotPanel.updatePoints(model.points);
        outputComboBox.setSelectedIndex(model.outputIndex);
        featureComboBox.setSelectedIndex(model.featureIndex);
        liveToggle.setSelected(model.isStreaming);
    }

    /**
     * This method is called from within the constructor to  the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plotPanel = new wekimini.gui.PlotPanel();
        outputComboBox = new javax.swing.JComboBox<>();
        featureComboBox = new javax.swing.JComboBox<>();
        liveToggle = new javax.swing.JCheckBox();
        closeButton = new javax.swing.JButton();

        plotPanel.setPreferredSize(new java.awt.Dimension(500, 100));

        javax.swing.GroupLayout plotPanelLayout = new javax.swing.GroupLayout(plotPanel);
        plotPanel.setLayout(plotPanelLayout);
        plotPanelLayout.setHorizontalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        plotPanelLayout.setVerticalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        outputComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputComboBoxActionPerformed(evt);
            }
        });

        featureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featureComboBoxActionPerformed(evt);
            }
        });

        liveToggle.setText("Streaming");
        liveToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liveToggleActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(featureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(liveToggle)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(featureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liveToggle)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        delegate.closeButtonPressed(model);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void outputComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputComboBoxActionPerformed
        // TODO add your handling code here:
        int i = outputComboBox.getSelectedIndex();
        if(i > 0)
        {
            model.outputIndex = i;
            delegate.modelChanged(model);
        }
    }//GEN-LAST:event_outputComboBoxActionPerformed

    private void featureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featureComboBoxActionPerformed
        // TODO add your handling code here:
        int i = featureComboBox.getSelectedIndex();
        if(i > 0)
        {
            model.featureIndex = i;
            delegate.modelChanged(model);
        }
    }//GEN-LAST:event_featureComboBoxActionPerformed

    private void liveToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liveToggleActionPerformed
        // TODO add your handling code here:
        model.isStreaming = liveToggle.isSelected();
        delegate.modelChanged(model);
    }//GEN-LAST:event_liveToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> featureComboBox;
    private javax.swing.JCheckBox liveToggle;
    private javax.swing.JComboBox<String> outputComboBox;
    private wekimini.gui.PlotPanel plotPanel;
    // End of variables declaration//GEN-END:variables
}
